version: "2.0"
services:
  api:
    hostname: api
    container_name: api
    build: ./docker/api
    ports: 
      - 9001:9001
    volumes:
      - ./src:/myapp
    links:
      - mysql

  mysql:
    hostname: mysql
    container_name: catalog_mysql
    image: mysql/mysql-server:5.7
    volumes:
      - ./docker/mysql/:/myapp/mysql/
    environment:
      - MYSQL_DATABASE=catalog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=supersecret